# Predefined Summoner Settings
SUMMONER_REGION = ''
SUMMONER_NAME = ''

# Global API Key
API_KEY = ''

# API Versions
API_SUMMONER_VERSION = 'v1.4'
API_CHAMPION_VERSION = 'v1.2'
API_MATCHHISTORY_VERSION = 'v2.2'
API_LEAGUE_VERSION = 'v2.5'
API_STATS_VERSION = 'v1.3'